# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ov < Formula
  desc "Zero-knowledge, quantum-safe secret manager for AI coding agents"
  homepage "https://opaquevault.com"
  version "0.6.4"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.opaquevault.com/v0.6.4/ov_darwin_amd64.tar.gz"
      sha256 "8d6e18eac8cc3755641f7398c78ad16cea15a1beaf903f388eadadbe6c482698"

      define_method(:install) do
        bin.install "ov"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.opaquevault.com/v0.6.4/ov_darwin_arm64.tar.gz"
      sha256 "a08f86429bcd2d973bc0d8ca7116167327381a23d3df6f302f465e993ec7b7ae"

      define_method(:install) do
        bin.install "ov"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.opaquevault.com/v0.6.4/ov_linux_amd64.tar.gz"
      sha256 "e3d7a498c8b05e0cc6a0a8d139c3ee1fd0b1a10b36f973eb9b3a8f04aeaca4fb"
      define_method(:install) do
        bin.install "ov"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.opaquevault.com/v0.6.4/ov_linux_arm64.tar.gz"
      sha256 "fd32a3078a37cb51920a2632975ab3c3824b0a2b8cd7a44f4b04aa14c5a46af6"
      define_method(:install) do
        bin.install "ov"
      end
    end
  end

  def caveats
    <<~EOS
      Run this in every project that uses OpaqueVault:
        ov init

      Auto-detects Claude Code, Cursor, Windsurf, GitHub Copilot, Aider, Zed,
      Continue, and Cline — and writes secret-handling rules to each one.

      For a global rule that applies to all projects in Claude Code:
        ov init --global

      Then authenticate:
        ov auth login
    EOS
  end

  test do
    system "#{bin}/ov", "--version"
  end
end
