# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ov < Formula
  desc "Zero-knowledge, quantum-safe secret manager for AI coding agents"
  homepage "https://opaquevault.com"
  version "0.7.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.opaquevault.com/v0.7.3/ov_darwin_amd64.tar.gz"
      sha256 "04c93de9a04dcef3529ebda87d2e51ab467f346f9e8f3100d562cd5f36cba2c1"

      define_method(:install) do
        bin.install "ov"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.opaquevault.com/v0.7.3/ov_darwin_arm64.tar.gz"
      sha256 "f1b80596c1220d4f9e63578f979c4f5602dd030aa6fdeab01db77b50481bdfc5"

      define_method(:install) do
        bin.install "ov"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.opaquevault.com/v0.7.3/ov_linux_amd64.tar.gz"
      sha256 "4acd6b231b513a20ef89b633dc5870779bae4bb46ce5c494af4e58ecf5962f0b"
      define_method(:install) do
        bin.install "ov"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.opaquevault.com/v0.7.3/ov_linux_arm64.tar.gz"
      sha256 "49a1c6bcf7826d4096eeec82b0c1299aac88ecbccc0b91396192032fca0dd0c2"
      define_method(:install) do
        bin.install "ov"
      end
    end
  end

  def caveats
    <<~EOS
      Run this in every project that uses OpaqueVault:
        ov init

      Auto-detects Claude Code, Cursor, Windsurf, GitHub Copilot, Aider, Zed,
      Continue, and Cline — and writes secret-handling rules to each one.

      For a global rule that applies to all projects in Claude Code:
        ov init --global

      Then authenticate:
        ov auth login
    EOS
  end

  test do
    system "#{bin}/ov", "--version"
  end
end
