# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ov < Formula
  desc "Zero-knowledge, quantum-safe secret manager for AI coding agents"
  homepage "https://opaquevault.com"
  version "0.11.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://releases.opaquevault.com/v0.11.0/ov_darwin_amd64.tar.gz"
      sha256 "38e7edcff82b0bcfcec499e6989c77f67dbf5032c9d33be929158af2fdb0be9a"

      define_method(:install) do
        bin.install "ov"
      end
    end
    if Hardware::CPU.arm?
      url "https://releases.opaquevault.com/v0.11.0/ov_darwin_arm64.tar.gz"
      sha256 "4da5858476f30611bf23a964a2516fe31e9aaa574d79b12b8501bf6f56de6d8c"

      define_method(:install) do
        bin.install "ov"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://releases.opaquevault.com/v0.11.0/ov_linux_amd64.tar.gz"
      sha256 "f7a235daf98708605e6d420870db99b0037b0d7d8d05a0e3afb00a8af26be897"
      define_method(:install) do
        bin.install "ov"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://releases.opaquevault.com/v0.11.0/ov_linux_arm64.tar.gz"
      sha256 "8b977f9eb437e750c0a2f02823ac12217a60dd556090b37683066b78d38eb714"
      define_method(:install) do
        bin.install "ov"
      end
    end
  end

  def caveats
    <<~EOS
      Run this in every project that uses OpaqueVault:
        ov init

      Auto-detects Claude Code, Cursor, Windsurf, GitHub Copilot, Aider, Zed,
      Continue, and Cline — and writes secret-handling rules to each one.

      For a global rule that applies to all projects in Claude Code:
        ov init --global

      Then authenticate:
        ov auth login
    EOS
  end

  test do
    system "#{bin}/ov", "--version"
  end
end
